"""Factor-contribution analysis toolkit public API."""

from .contributor import ContributorRow, combine_contributors, rank_contributors
from .estimator import Estimator
from .hypothesis import (
    BinaryHypothesisResult,
    BinaryHypothesisTest,
    evaluate_binary_hypotheses,
    evaluate_binary_hypothesis,
)
from .results import (
    AssessmentResult,
    BurdenRankingEntry,
    BurdenRankingResult,
    ContrastResult,
    FactorialCellResult,
    FactorialMarginalResult,
    FactorialMatrixResult,
    FeatureAttribution,
    HypothesisAssessment,
    PartitionWarning,
    RegimeAssessment,
    RegimeSummary,
)
from .spec import (
    AttributionSpec,
    CategoricalHypothesis,
    ContinuousHypothesis,
    FactorialCrossing,
    Hypothesis,
    PredictionFeature,
    Regime,
)
from .stats import (
    OddsRatioResult,
    RiskDifferenceResult,
    RiskRatioResult,
    agresti_caffo_risk_difference,
    baptista_pike_odds_ratio,
    haldane_anscombe_odds_ratio,
    katz_risk_ratio,
    koopman_risk_ratio,
    miettinen_nurminen_risk_difference,
    risk_difference_with_guardrail,
)

__all__ = [
    "AssessmentResult",
    "AttributionSpec",
    "BinaryHypothesisResult",
    "BinaryHypothesisTest",
    "BurdenRankingEntry",
    "BurdenRankingResult",
    "CategoricalHypothesis",
    "ContributorRow",
    "ContinuousHypothesis",
    "ContrastResult",
    "RegimeSummary",
    "Estimator",
    "FactorialCellResult",
    "FactorialCrossing",
    "FactorialMarginalResult",
    "FactorialMatrixResult",
    "FeatureAttribution",
    "Regime",
    "Hypothesis",
    "HypothesisAssessment",
    "RegimeAssessment",
    "OddsRatioResult",
    "RiskDifferenceResult",
    "RiskRatioResult",
    "agresti_caffo_risk_difference",
    "baptista_pike_odds_ratio",
    "combine_contributors",
    "evaluate_binary_hypotheses",
    "evaluate_binary_hypothesis",
    "haldane_anscombe_odds_ratio",
    "katz_risk_ratio",
    "koopman_risk_ratio",
    "miettinen_nurminen_risk_difference",
    "PartitionWarning",
    "PredictionFeature",
    "rank_contributors",
    "risk_difference_with_guardrail",
]
